project: sts
name: shchoi
path:
    train_path: /opt/ml/wandb_base_project/data/petition_aug.csv
    dev_path: /opt/ml/wandb_base_project/data/dev.csv
    test_path: /opt/ml/wandb_base_project/data/dev.csv
    predict_path: /opt/ml/wandb_base_project/data/test.csv

data:
    shuffle: True
    augmentation: # adea, bt 등등
  
metric: PearsonCorrCoef
model:
    model_name: beomi/KcELECTRA-base
    saved_name: base_model

train:
    seed: 42
    gpus: 1
    batch_size: 16
    max_epoch: 30
    learning_rate: 0.0000074842028984369805
    logging_step: 1

loss: L1Loss

optimizer: #torch.optim에 존재하는 optimizer만 사용가능. 함수명과 args의 이름이 정확히 일치해야 합니다.
    name: AdamW
    args:
        weight_decay: 0.004585548152280841
        amsgrad: False

lr_scheduler: #torch.optim.lr_cheduler에 존재하는 lr_scheduler만 사용가능.
    name: StepLR
    args:
        step_size: 40
        gamma: 0.1



 