program: train.py
method: grid
metric:
    goal: maximize
    name: test_pearson
parameters:
    train.learning_rate:
        values: [0.00001, 0.00002, 0.00003]
    optimizer.args.weight_decay:
        values: [0.001, 0.002, 0.003]
    train.max_epoch:
       values: [1, 2, 3]
    lr_scheduler.args.step_size:
       values: [30, 40, 50]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - base_config
  - ${args_no_hyphens}