program: train.py
method: random
metric:
    goal: maximize
    name: test_pearson
parameters:
    train.learning_rate:
        distribution: uniform
        min: 0.000001
        max: 0.00001
    optimizer.args.weight_decay:
        distribution: uniform
        min: 0.001
        max: 0.01
    train.max_epoch:
        values: [30]
    lr_scheduler.args.step_size:
        values: [30, 40, 50]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - base_config
  - ${args_no_hyphens}