
wandb:
  project: sts
  name: jalee
  info: AEDA_k-fold_special_token # 기타 적용사항

path:
  train_path: ./data/raw_data/train.csv #./data/aug_data/train_auged.csv
  dev_path: ./data/raw_data/dev.csv
  test_path: ./data/raw_data/dev.csv
  predict_path: ./data/raw_data/test.csv

data:
  shuffle: True

model:
  name: beomi/KcELECTRA-base # klue/roberta-small | beomi/KcELECTRA-base | klue/bert-base | xlm-roberta-base | jhgan/ko-sroberta-sts
  saved_name: baseline_1 # 저장할 모델 이름

loss_func: L1Loss # L1Loss | ...

train:
  seed: 42
  gpus: 1
  batch_size: 16
  max_epoch: 2
  learning_rate: 1.0e-05
  bce: True
  k: 1
  split_seed: 12345
  num_splits: 10

optimizer: AdamW

scheduler: StepLR

callback_monitor: val_loss



