program: contrastive_train.py
method: bayes # grid | random | bayes
metric:
  name: val_pearson
  goal: maximize
parameters:
  sweep:
    values: [1]
  batch_size:
    values: [8]
  margin:
    values: [1.0, 1.5, 2.0, 2.5, 3.0]
  seed:
    distribution: int_uniform
    min: 1
    max: 512
  

