program: train.py
method: random # grid | random | bayes
metric:
  name: val_pearson
  goal: maximize
parameters:
  learning_rate:
    min: 0.0001
    max: 0.001
  optimizer:
    values: ['adam', 'sgd']
  dropout:
    values: [0.1, 0.2, 0.3, 0.4]
  max_epoch:
    values: [10]
  sweep:
    values: [1]
  batch_size:
    values: [4, 8, 16, 32]